# 2	Technical Robustness and Safety (ROB)

A crucial component of achieving Trustworthy AI is technical robustness, which is closely linked to the principle of prevention of harm. Technical robustness requires that AI systems be developed with a preventative approach to risks and in a manner such that they reliably behave as intended while minimising unintentional and unexpected harm, and preventing unacceptable harm. This should also apply to potential changes in their operating environment or the presence of other agents (human and artificial) that may interact with the system in an adversarial manner. In addition, the physical and mental integrity of humans should be ensured.

## 2.1 Resilience to Attack and Safety

AI systems, like all software systems, should be protected against vulnerabilities that can allow them to be exploited by adversaries, e.g. hacking. Attacks may target the data (data poisoning), the model (model leakage) or the underlying infrastructure, both software and hardware. If an AI system is attacked, e.g. in adversarial attacks, the data as well as system behaviour can be changed, leading the system to make different decisions, or causing it to shut down altogether. Systems and data can also become corrupted by malicious intention or by exposure to unexpected situations. Insufficient security processes can also result in erroneous decisions or even physical harm. For AI systems to be considered secure, possible unintended applications of the AI system (e.g. dual-use applications) and potential abuse of the system by malicious actors should be taken into account, and steps should be taken to prevent and mitigate these.

| **Question**        | **Considerations**                     |
|----------------------|---------------------------------------|
| Describe how you identified, simulated, and assessed the potential security risks of planned models? Particularly, describe measures taken to mitigate the risk of common adversarial attacks.| Could your models potentially affect fundamental rights: respect for human dignity, freedom, democracy, equality, rule of law, or respect for human rights?Adversarial attacks are an often-overlooked threat for AI systems. Especially in healthcare this leads to high risk for patients as data donors. For a taxonomy and terminology of attacks and their mitigations, see e.g. [3]. The same resource lists also attacks specific to generative AI.|
| Will the AI models created in the project be publicly released? If yes, elaborate where and what security measures are taken to prevent risks.| Publicly available datasets increase the risk of adversarial attacks that rely on access to the models.|

## 2.2 Fallback plan and general safety

AI systems should have safeguards that enable a fallback plan in case of problems. This can mean that AI systems switch from a statistical to rule-based procedure, or that they ask for a human operator before continuing their action. It must be ensured that the system will do what it is supposed to do without harming living beings or the environment. This includes the minimisation of unintended consequences and errors. In addition, processes to clarify and assess potential risks associated with the use of AI systems, across various application areas, should be established. The level of safety measures required depends on the magnitude of the risk posed by an AI system, which in turn depends on the system’s capabilities. Where it can be foreseen that the development process or the system itself will pose particularly high risks, it is crucial for safety measures to be developed and tested proactively.

| **Question**        | **Considerations**                     |
|----------------------|---------------------------------------|
| Describe the process how you clarified and assessed the risks of your models, the associated risk metrics and risk levels for unintended consequences and errors. In case you use synthetic data, describe whether models based on the original data and models based on synthetic data exhibit the same or different risks.| A minimum requirement for general safety is an overview of the risks and how they can be measured.|
| Describe the level of risk discerned: specifically threats to the AI models, regarding malicious use, misuse, or inappropriate use.| In a research setting, one of the most common questions will be how the use of the models could lead to unintended threatst/risks. For example, many funders now require open code/open data approaches, under which models will regularly be made publicly available.|
| What is the process for mitigating identified risks?| Next to identifying and assessing risk, it must be ensured that the risks are appropriately mitigated.|
| How will you obtain and assess feedback about your models and how will you incorporate it?| This is crucial, if potentially new risks that have been overlooked in the initial phase, there is a need for a feedback loop. Especially in a research setting, it needs to be ensured that feedback can still be received, even after staff, e.g. a PhD-student or postdoc, leave the associated lab.|

## 2.3 Accuracy

Accuracy pertains to an AI system’s ability to make correct judgements, for example to correctly classify information into the proper categories, or its ability to make correct predictions, recommendations, or decisions based on data or models. An explicit and well-formed development and evaluation process can support, mitigate and correct unintended risks from inaccurate predictions. When occasional inaccurate predictions cannot be avoided, it is important that the system can indicate how likely these errors are. A high level of accuracy is especially crucial in situations where the AI system directly affects human lives.

| **Question**        | **Considerations**                     |
|----------------------|---------------------------------------|
| In the resulting AI models, how is accuracy defined and tested, and what is the justification for use of  these metrics? If you are creating synthetic data: Describe why the accuracy compared to training the model on original data is sufficient, and how you came to that conclusion.| It is critical to define the right metrics for a given case to assess accuracy.|
| Describe how the robustness of the model results will be tested, ensured and documented?| Human oversight requires that other can audit your decisions and oversight mechanisms. Robustness, defined as a metric of the internal and external validity of AI models is a crucial indicator for the trustworthiness of the reported accuracy.|
| Describe all machine learning best practices that you have been following in your training and testing of the AI models.| Reported accuracies are trustworthy if broadly accepted best practices are followed during development. It is advisable to follow these and to report them when making models publicly available, or when publishing results.|
| If you are creating synthetic data: Describe your evaluation of whether the data generation is picking up spurious correlations (“Clever Hans” phenomenon)?| A 'Clever Hans' effect can occur when the developed models results are correct predictions which are based on incorrect features.[4]|

## 2.4 Reliability and Reproducibility

It is critical that the results of AI systems are reproducible, as well as reliable. A reliable AI system is one that works properly with a range of inputs and in a range of situations. This is needed to scrutinise an AI system and to prevent unintended harms. Reproducibility describes whether an AI experiment exhibits the same behaviour when repeated under the same conditions. This enables scientists and policy makers to accurately describe what AI systems do. Replication files can facilitate the process of testing and reproducing behaviours.

| **Question**        | **Considerations**                     |
|----------------------|---------------------------------------|
| Describe how you defined the ranges and inputs of your AI models.| Reliability can only be ensured if an AI system is used within the specifications that have been set during development.|
| Describe procedures for assessing the and results of the AI model´s replicability and reproducibility. Will these analyses be made publicly available or upon request?| Threats to reproducible science are, among others, publication bias, failure to control for bias, p-hacking, low statistical power, poor quality control[5].|
| Describe how you have assessed and mitigated the risk of data drift.| There are multiple examples of data drift in deployed medical AI systems and one article suggests that choosing more stable features (e.g., biological markers, blood pressure, heartrate) might decrease the risk of data drift compared to features impacted by social behaviour or organizational processes (e.g., time from hospitalization, ICD codes) [6].|
