# 6	Societal and Environmental Well-Being (SUS)

In line with the principles of fairness and prevention of harm, the broader society, other sentient beings and the environment should be also considered as stakeholders throughout the AI system’s life cycle. Sustainability and ecological responsibility of AI systems should be encouraged, and research should be fostered into AI solutions addressing areas of global concern, such as for instance the Sustainable Development Goals. Ideally, AI systems should be used to benefit all human beings, including future generations.

## 6.1	Sustainable and environmentally friendly AI

AI systems promise to help tackling some of the most pressing societal concerns, yet it must be ensured that this occurs in the most environmentally friendly way possible. The system’s development, deployment and use process, as well as its entire supply chain, should be assessed in this regard, e.g. via a critical examination of the resource usage and energy consumption during training, opting for less harmful choices. Measures securing the environmental friendliness of AI systems’ entire supply chain should be encouraged.

| **Question**        | **Considerations**                     |
|----------------------|---------------------------------------|
| Describe how the energy consumption related to the training and testing of the AI models has been estimated, logged, documented, and/or shared.| The Datavizta emissions calculator can be used to estimate the emissions related to the use of different clouds or hardware [17].|
| Describe what negative impacts your AI development could have on the environment and your measures to reduce the environmental impact of your model development.| You may want to consider an SOP for decreasing unnecessary resource usage; or switching to the the most environmentally friendly type of energy was consumed in the development of the AI model|
| If you use HE, describe how you have ensured the minimal amount of features to avoid unnecessary heavy computations that might impact sustainability? [18, p. 2]| The combination of machine learning and HE is known to be very resource intensive with increasing numbers of features.|

## 6.2	Social impact

Ubiquitous exposure to social AI systems in all areas of our lives (be it in education, work, care or entertainment) may alter our conception of social agency, or impact our social relationships and attachment. While AI systems can be used to enhance social skills, they can equally contribute to their deterioration. This could also affect people’s physical and mental wellbeing. The effects of these systems must therefore be carefully monitored and considered.

**This sub-item is not applicable for this toolbox.**

## 6.3	Society and democracy

Beyond assessing the impact of an AI system’s development, deployment and use on individuals, this impact should also be assessed from a societal perspective, taking into account its effect on institutions, democracy and society at large. The use of AI systems should be given careful consideration particularly in situations relating to the democratic process, including not only political decision-making but also electoral contexts.

| **Question**        | **Considerations**                     |
|----------------------|---------------------------------------|
| Describe your assessment whether the AI model has an impact on institutions or the society.| You may want to consider the effect of the model on the healthcare system, e.g. on a governance, economic, and staffing level. You may want to consider the impact of your AI model on human work and work arrangements, in the healthcare setting for example effects on de-skilling.|
